#!/usr/bin/env python3
"""一次性生成 SPA 黄金向量（不是 CI 的一部分，不要自动执行）。

用途：把 Python 参考实现（../vpn_client.py 的 build_spa）的输出固化成 Go 侧
可逐字节对拍的向量。改动了协议或怀疑 Go 实现有偏差时，重新跑一遍即可：

    python enagent/spa/testdata/gen_reference.py enagent/spa/reference_vectors_test.go

为了确定性，脚本会：
  * 把 os.urandom 固定成 0102030405060708（salt 可控）
  * 随机数种子固定为 42,时间固定为 1700000000
需要 vpn_client.py 所在目录能被 import。

⚠️ 生成的向量里用的是**合成学号** 202500000000，绝不要换成真实学号。
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import random
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
VPNDIR = REPO
AUTHSERVER = REPO.parent / "authserver_login"

FIXED_SALT = bytes.fromhex("0102030405060708")
FIXED_TIME = 1700000000
FIXED_SEED = 42

# 合成凭据：仓库里绝不出现真实学号。
USER = "202500000000"
CASES = [
    ("hmac-tcp443", "tcp/443", True),
    ("hmac-udp53", "udp/53", True),
    ("nohmac-tcp443", "tcp/443", False),
]


def b64s(data: bytes) -> str:
    return base64.b64encode(data).decode().rstrip("=")


def main() -> int:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("reference_vectors_test.go")

    sys.path.insert(0, str(VPNDIR))
    random.seed(FIXED_SEED)
    os.urandom = lambda n: FIXED_SALT  # noqa: ARG005
    import vpn_client as vc  # noqa: E402

    vc.time.time = lambda: FIXED_TIME

    key = bytes.fromhex(vc.SPA_KEY_HEX)
    kiv = vc.derive_kiv(key, FIXED_SALT)

    vectors = []
    for name, access, use_hmac in CASES:
        # 复刻 build_spa 的前半段，把不可控的 rand_val 单独取出来，
        # 以便 Go 侧用等价的 Rand 复现同一份明文。
        rand_val = "".join(random.choice("0123456789") for _ in range(16))
        msg = ":".join([
            rand_val,
            b64s(USER.encode()),
            str(FIXED_TIME),
            vc.PROTO_VERSION,
            str(vc.MSG_TYPE_ACCESS),
            b64s(access.encode()),
        ])
        plain = (msg + ":" + b64s(hashlib.sha256(msg.encode()).digest())).encode()
        cipher = vc.aes256_cbc_encrypt(kiv[:32], kiv[32:48], plain)
        full = b64s(b"Salted__" + FIXED_SALT + cipher)
        want = full[10:]
        if use_hmac:
            want += b64s(hmac.new(key, full.encode(), hashlib.sha256).digest())

        vectors.append({
            "name": name,
            "access": access,
            "use_hmac": use_hmac,
            "rand_val": rand_val,
            "want": want,
        })

    lines = [
        "// Code generated by enagent/spa/testdata/gen_reference.py; DO NOT EDIT.",
        "",
        "package spa",
        "",
        "// referenceVectors 由 Python 参考实现（vpn_client.build_spa）离线生成，",
        "// 用于逐字节对拍 Go 实现。salt 固定为 0102030405060708、时间固定为",
        "// 1700000000、学号为合成值，因此向量是确定性的。",
        "var referenceVectors = []referenceVector{",
    ]
    for v in vectors:
        use_hmac_go = "true" if v["use_hmac"] else "false"
        lines += [
            "\t{",
            f"\t\tname:    {v['name']!r},",
            f"\t\tuser:    {USER!r},",
            f"\t\taccess:  {v['access']!r},",
            "\t\tsaltHex: \"0102030405060708\",",
            f"\t\trandVal: {v['rand_val']!r},",
            f"\t\tuseHMAC: {use_hmac_go},",
            f"\t\twantKIV: {kiv[:48].hex()!r},",
            f"\t\twant:    {v['want']!r},",
            "\t},",
        ]
    lines += ["}", ""]

    # 用 Go 的原始字符串字面量更可读，但向量里含 + / = 等字符，
    # 普通双引号字符串最安全。
    text = "\n".join(lines).replace("'", '"')
    out_path.write_text(text, encoding="utf-8")

    # 生成的源码要能被 CI 的 gofmt 检查通过，直接在这里格式化。
    try:
        import subprocess
        subprocess.run(["gofmt", "-w", str(out_path)], check=True)
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"提示: gofmt 未执行（{exc}），请手动跑 gofmt -w {out_path}")

    print(f"已写入 {out_path}（{len(vectors)} 条向量）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
