// Code generated by enagent/spa/testdata/gen_reference.py; DO NOT EDIT.

package spa

// referenceVectors 由 Python 参考实现（vpn_client.build_spa）离线生成，
// 用于逐字节对拍 Go 实现。salt 固定为 0102030405060708、时间固定为
// 1700000000、学号为合成值，因此向量是确定性的。
var referenceVectors = []referenceVector{
	{
		name:    "hmac-tcp443",
		user:    "202500000000",
		access:  "tcp/443",
		saltHex: "0102030405060708",
		randVal: "1043321819600133",
		useHMAC: true,
		wantKIV: "f501b3cfadd72d213ffef322b4c82c8fc6267bee928af335e9bcdba79ab71877fad3d9634096bb33eaf329c033dfdb3f",
		want:    "8BAgMEBQYHCP+okvuIjojwJJtyRtVHdFsOE8tnP56dc7CTK4zOtqsiAdRtDLlC28U33mSXX8yqRIO3i7AkUT/VQtHLhkdlRbW4PW2CnP/E4HxtTw5b3xmMtwgMfWkLjV0Wp+8L7b6ITxqRWI9j2h4J56KYvzlmIqAWSjruQstqNLFPcX5SrgNF/Z2JjcBx3BOS1PmPvUUMjs",
	},
	{
		name:    "hmac-udp53",
		user:    "202500000000",
		access:  "udp/53",
		saltHex: "0102030405060708",
		randVal: "8908386379402654",
		useHMAC: true,
		wantKIV: "f501b3cfadd72d213ffef322b4c82c8fc6267bee928af335e9bcdba79ab71877fad3d9634096bb33eaf329c033dfdb3f",
		want:    "8BAgMEBQYHCGPo3Pz1eTj9Z6bdHoiWgY3+wKrFUtZhle0wD7esp2a4RAPKdg8hNWMCBRpszYz5db/VbbZ5hr6jsGadD3TPlQ5bqMce06NNPqPvRQmd+u5ftr8r+VlH2n/0KeBe1ewu4GKfqAJUYidxcizL8n7wh80xq+DOjFKziafGyHBePY+CfI6DAGRCdh5OOs0azrufpc",
	},
	{
		name:    "nohmac-tcp443",
		user:    "202500000000",
		access:  "tcp/443",
		saltHex: "0102030405060708",
		randVal: "2351161559407816",
		useHMAC: false,
		wantKIV: "f501b3cfadd72d213ffef322b4c82c8fc6267bee928af335e9bcdba79ab71877fad3d9634096bb33eaf329c033dfdb3f",
		want:    "8BAgMEBQYHCOcrZiibq6mHFwmmfv9QyReW4mv33TKEmssmRwtNIPxe7q5MZ3Kwr1Jb+r86i0NuUUrHnEnlEVIF7t+Fzia7bFDLPU2f5qyrpmEaXqxTpFR7eKpr6BPaj2H8rwSEc0Jcm16Rq4R/w9HhzJDoqovIJ+I",
	},
}
